### ISSUE TITLE
Sorting CSS classes not toggled correctly

### ISSUE THREAD

**Issue by vaultor** [svivian/sv-sortable-js#1]
When applying sort twice (ascending then descending), both CSS classes `sorting-asc sorting-desc` are applied at the same time.
Expected to only apply either class in step with the `data-sort-dir` value.

Actual:
`<th scope="col" class="data-head text-left sorting-asc sorting-desc" data-sort-type="string" data-sort-dir="desc">Description</th>`

Expected:
`<th scope="col" class="data-head text-left sorting-desc" data-sort-type="string" data-sort-dir="desc">Description</th>`

**Comment by svivian** [comment]
Thanks for the report. Out of interest, how did you find my libraries? I never got around to publicizing them anywhere.

**Comment by vaultor** [comment]
From Google :)
More specifically, I came across `sv-sortable` and `sv-filtable` from this [website](https://www.cssscript.com/tag/table-sort/).
